### ISSUE TITLE
requests error, connection aborted

### ISSUE THREAD

**Issue by arim215** [arim215/nhl_goal_light#6]
Traceback (most recent call last):
  File "auto_nhl_goal.py", line 108, in <module>
    (game_id,team_abr)=check_if_game(team)
  File "auto_nhl_goal.py", line 49, in check_if_game
    MTL=requests.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

**Comment by arim215** [comment]
not in this new version (pulled api_source branch)
